[tool.pysen]
version = "0.10"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
py_version = "py27"
isort_known_first_party = ["genmypy"]
[tool.pysen.lint.source]
  excludes = ["tests/integration_tests/expected", ".tox"]
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]
